const MAX_FILE_UPLOADS = 5;
const MAX_FILE_SIZE = 10 * 1024 * 1024;
const MAX_CONTENT_LENGTH = 350;
const MIN_PASS_LENGTH = 8;
const MIN_FIRST_LAST_NAME_LENGTH = 2;
const MAX_FIRST_LAST_NAME_LENGTH = 20;
const PAST_30_DAYS = 30 * 24 * 60 * 60 * 1000;

module.exports = {
	MAX_FILE_UPLOADS,
	MAX_FILE_SIZE,
	MAX_CONTENT_LENGTH,
	MIN_PASS_LENGTH,
	MIN_FIRST_LAST_NAME_LENGTH,
	MAX_FIRST_LAST_NAME_LENGTH,
	PAST_30_DAYS,
};
